### ISSUE TITLE
Inline function call out of a map is recognized as stylesheet function call

### ISSUE THREAD

**Issue by jperterm** [DeltaXML/vscode-xslt-tokenizer#106]
Calling an inline function which is in a map does produce the error _XPath: Function: 'foo' with 0 arguments not found_.

```xsl
<xsl:template name="test">
        <xsl:variable name="map" as="map(*)" select="
            map{
                'foo': function(){'bar'}
            }"/>

        <!-- XPath: Function: 'foo' with 0 arguments not found -->
        <xsl:sequence select="$map?foo()"/>

        <!-- Alternative is fine -->
        <xsl:sequence select="($map?foo)()"/>
</xsl:template>
```

**Comment by pgfearo** [comment]
Thanks for reporting this issue., I will investigate and report back.

**Comment by pgfearo** [comment]
The linter should not report a problem as it should not attempt to resolve `foo()` Map lookup needs the dynamic context that is only available at run time.

**Comment by pgfearo** [comment]
Fixed
