### ISSUE TITLE
Goto Definition in modes not work

### ISSUE THREAD

**Issue by kvdubina** [DeltaXML/vscode-xslt-tokenizer#107]
in Futures:
Goto Definition — For all symbol references like variables, parameters, functions, modes, accumulators etc.

Ехаmple:
```
<xsl:apply-templates select="node" mode="mode1"/>

<xsl:template match="node" mode="mode1">
<xsl:value-of select="name"/>
</xsl:template>
```

Goto on mode1 in  <xsl:apply-templates select="node" mode="mode1"/> does not go to <xsl:template match="node" mode="mode1">

But it works for variables

Video
https://user-images.githubusercontent.com/16345533/189931333-aa1f8459-ebe8-43e4-9585-ee12d9ff034b.mov

**Comment by pgfearo** [comment]
Thanks for reporting this bug. In XSLT, modes are defined quite differently than other symbols, this possibly accounts for the problem. 

With other symbols there can be only one definition, with XSLT I suppose we can say that there's a mode definition on each `xsl:template` instruction where a mode name is specified. The `xsl:mode` instruction should also be considered a 'definition' if it has a `name` attribute.

The `xsl:apply-templates` instruction with a named mode  can therefore be considered a symbol reference.

**Comment by pgfearo** [comment]
The `Rename Symbol` feature is related to this. There's a bug when renaming a mode - the mode name change is repeated at the cursor position

**Comment by pgfearo** [comment]
## Summary of fixes

### Goto Definition - for modes
-  'Goto Definition' does not quite fit with XSLT modes (as there is no single definition), but this is implemented as follows:
   - if on `xsl:mode` instruction - do nothing as this can be considered the definition
   - if on `xsl:template` instruction: 
      - go to `xsl:mode` instruction if it exists, or: 
      - go to topmost `xsl:apply-templates` instruction with same mode in same module
   - if on `xsl:apply-templates` instruction: 
      - go to `xsl:mode` instruction if it exists, or: 
      - go to topmost `xsl:template` instruction with same mode in same module

 ###  Goto References - for modes
- Did not work reliably as:
   - It required 'Goto Defintion' functionality that did not work properly
   - It did not account for multiple modes in a single `mode` attribute of an `xsl:template` instruction 


 ### Rename Symbols - for modes
- Did not work reliably as It uses 'Goto References' functionality that did not work properly
