### ISSUE TITLE
xsltFile based on xml-stylesheet

### ISSUE THREAD

**Issue by otichy** [DeltaXML/vscode-xslt-tokenizer#114]
Different XML files in my project require different xsl transformations. Currently, I need to create new task for each, but it would be nice to have just one, which would have the xsltFile variable based on the XSL stylesheet association of the respective XML like:

`<?xml-stylesheet type="text/xsl" href="xsltFile">`

This is possible e.g. in oXygen and seems very intuitive. In fact, it would be great if this could be in some default task setting so that you would not even need to edit the task.json in a lot of cases (that would make it much more approachable to new users or users coming over from e.g. oXygen).

**Comment by pgfearo** [comment]
I will investigate adding this feature.

My first instinct would be to allow the end-user to trigger the XSLT transform by:
1.  invoking a new command: 'Run XSLT task using xml-stylesheet processing instruction' or
2. pressing a new 'Run XSLT task' button

**Comment by pgfearo** [comment]
To help with XSLT file selection for tasks, I've now added a set of commands that provide file-selection input for a task. For example, you can use the property 
```json 
"xsltFile": "${command:xslt-xpath.pickXsltFile}"
```
This command will show a 'recently used' list (preserved for each workspace), a 'current file' and a 'Pick File' option. The 'Pick File' option will allow you to use a File Explorer to select a file, this is initially located in the current file's directory. Here's an example 'QuickPick' list with the options:

![newest-pickFiles](https://user-images.githubusercontent.com/2734234/212376511-2fa25d87-9212-4664-b8e9-144f69e150a9.png)

Is this sufficient, or would you prefer:
1. to see the `xml-stylesheet` entry in the 'QuickPick' list also, or
2. to have a dedicated command for `<?xml-stylesheet...` like `${command:xslt-xpath.stylesheetInstruction}` ?

**Comment by otichy** [comment]
This looks great! 

Honestly, I would prefer to also have 1. (which I suppose would be the top choice next time). This would make it almost as smooth with a keyboard as 2. and therefore 2. may not be necessary.

**Comment by pgfearo** [comment]
OK, I'll look into implementing proposal 1.  Yes, the most recently selected XSLT becomes the top-choice. A maximum of 10 items are on the recently used list, after the oldest item is removed to keep the list count at 10. 

Naturally, the recently used list is preserved between VS Code sessions. This list can however be cleared using the 'Clear Recentluy Used' item on the 'QuickPick' list.

**Comment by pgfearo** [comment]
In Release 1.5.0 there's now an `xml-stylesheet` entry in the file 'pick-list' for the `${command:xslt-xpath.pickXsltFile}` command - provided the processing instruction exists in the current document and the `type` attribute is `text/xsl`. The `href` pseudo-attribute resolved relative to the current file path is shown in the list.

If this is picked it's used in the XSLT Task and also added to the 'recently used' files list.

**Comment by otichy** [comment]
I have just tested this and have one question, what if the file is not local? Now it seems to add the URL to the folder's local address. Maybe if it detects http(s) at the beginning it should make it absolute without the folder address?

**Comment by pgfearo** [comment]
Yes, all hrefs are assumed to reference local files. If they're recognised as relative file references they're resolved from the current editor's file URI and converted back to a file-system path. I will look into supporting https:// and http:// as identifiers for absolute local paths - I don't generally deal with such XML files so haven't come across this usage myself.

**Comment by otichy** [comment]
> Yes, all hrefs are assumed to reference local files. If they're recognised as relative file references they're resolved from the current editor's file URI and converted back to a file-system path. I will look into supporting https:// and http:// as identifiers for absolute local paths - I don't generally deal with such XML files so haven't come across this usage myself.

Hi, just checking, any luck with having a remote XSL?
