### ISSUE TITLE
False error when constructing default namespace

### ISSUE THREAD

**Issue by jperterm** [DeltaXML/vscode-xslt-tokenizer#120]
According to the XSLT (3.0) spec `<xsl:namespace>` requires a `name` attribute, but its value can be zero-length effectively to create a default namespace node.

The following XSLT causes the false error `XSLT: Invalid XSLT name: ''` for the case described:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes="#all" version="3.0">
    <xsl:template match="/*" mode="#all">
        <element>
            <xsl:namespace name="" select="'urn:default-namespace'"/>
        </element>
    </xsl:template>
</xsl:stylesheet>
```

**Comment by pgfearo** [comment]
Thanks for reporting this problem. The linter was treating the `name` attribute of `xsl:namespace` the same as for other XSLT instructions where `name` must have a non-empty string value. 

The issue has been fixed and is in the latest release: 1.5.8.
