### ISSUE TITLE
Support Saxon's SQL extension functions

### ISSUE THREAD

**Issue by jperterm** [DeltaXML/vscode-xslt-tokenizer#132]
I would appreciate if the VSC extension supports Saxon's SQL extension functions for the following benefits:

- Prevent errors like
  
  > XPath: Function: 'sql:prepared-query' with 2 arguments not found
  
- Code completion
- Check names/signatures
- Give signature hints

Namespace: `http://saxon.sf.net/sql`

Functions:

- `connect#1`
- `delete#3`
- `execute#2`
- `insert#3`
- `prepared-query#2`
- `prepared-statement#2`
- `query#3`
- `query#4`
- `update#4`

See also: https://www.saxonica.com/documentation11/index.html#!functions/sql

Let me know, if I can do/prepare something for this to work. Looking at the code it seems that this could be added without much effort even by myself.

**Comment by pgfearo** [comment]
I will schedule this SQL function support to be added in the next release.

**Comment by pgfearo** [comment]
I've updated the data for code completion and checking of names/signatures for the SQL functions, ready for release. The SQL function signature help will be provided in a later release once I've implemented a helpProvider for all functions, but this might not be for a while.

**Comment by jperterm** [comment]
Thanks so much, Phil!
