### ISSUE TITLE
Usage on OSS-variant of VSCode

### ISSUE THREAD

**Issue by hathiphant** [DeltaXML/vscode-xslt-tokenizer#137]
Is it planned to publish the extension on OpenVSX (for OSS variants of VSCode, like VSCodium or Theia)?

https://open-vsx.org/members
https://github.com/eclipse/openvsx

Thanks you very much,

**Comment by pgfearo** [comment]
This is an open source project so there would be no problems if this extension were made available on alternatives to the Visual Studio Code Marketplace.

That said, there are no immediate plans here to publish for the suggested alternatives. 

From a personal perspective, the VS Code marketplace has the benefit in that I can quickly see  the number of installs and downloads for the extension per day or per week. Knowledge that a reasonable number of others are using this extension (as well as myself) helps motivate me to continue improving the project. 

The install numbers are just about the only feedback I get so it wouldn't be helpful for me or the project to lose them.

As an interim measure I will try to be more disciplined about publishing each new release on [GitHub releases](https://github.com/DeltaXML/vscode-xslt-tokenizer/releases) so the build and source code for each release can be downloaded from here direct.

**Comment by hathiphant** [comment]
The reason for my question was also for easier discovery of your extension. By default, I use OSS variant of VSCode, then your extension was not suggested by a query for an XSLT extension.

For me, it is not a problem, because I can install Flathub non official VSCode (which will connect to Microsoft marketplace then find your extension).

I don't know if you prefer closing my bug or keeping it in the log, but don't hesitate to close my bug if it is not useful.

Thank you very much for your good extension. It seems very useful for modern XSLT.

**Comment by pgfearo** [comment]
OK thanks, I'll close this for now but hope to revisit this when I've the time to learn more about publishing to these alternative vscode  extension platforms.

**Comment by pgfearo** [comment]
Version 1.7.0 of the extension is now [published on OpenVSX](https://open-vsx.org/extension/deltaxml/xslt-xpath)

**Comment by hathiphant** [comment]
Thank you very much.
