### ISSUE TITLE
Support XSLT without prefix

### ISSUE THREAD

**Issue by maxtoroq** [DeltaXML/vscode-xslt-tokenizer#14]
![Capture](https://user-images.githubusercontent.com/2112966/85656843-43a1cb00-b67f-11ea-9e54-fe1017527b2f.PNG)

**Comment by pgfearo** [comment]
Strictly speaking you are correct, the editor should care only about the namespace, not the prefix. That said, this editor tries to encourage portable code and use well established practices for prefixes. Proposals for XSLT 4.0 also hint at more lax treatment of namespaces. This means that ‘xsl’ and ‘xs’ (the XML Schema namespace) are expected. It’s possible that, given enough time, an option will be added to allow all any prefix (or no prefix) to be used.

**Comment by maxtoroq** [comment]
What do you mean by portable, is my code not portable? Do you have a reference for XSLT 4 proposals?

**Comment by martin-honnen** [comment]
@maxtoroq, the proposal for XSLT 4 is at https://archive.xmlprague.cz/2020/files/xmlprague-2020-proceedings.pdf#page=121

**Comment by maxtoroq** [comment]
Relevant proposals to XSLT 4 are about types, path expressions and functions (QNames in content); not XSLT elements. It would require XSLT to move away from XML itself to give prefixes semantic.

**Comment by pgfearo** [comment]
I agree with everything you're saying.

**Comment by pgfearo** [comment]
It's probably best to think of the XSLT editor as a linter. So, it may sometimes add checks beyond what one would have in a specification-compliant XSLT compiler. Those additional checks are intended to ensure people can write code that can easily be shared in different projects. The code therefore needs some consistency.

As a side-note, it's relevant that enforcing specific prefixes provides significant benefits regarding code simplicity and performance/cpu-usage.

**Comment by pgfearo** [comment]
@maxtoroq I've looked up why I thought more lax namespace handling was being proposed for XSLT 4.0. This stems from Saxon-JS having an ns:##any option - where unprefixed names match against local names. This is targeted, I believe, at non-experienced XML people who don't understand namespaces, especially the default namespace.

So, this is not directly relevant to our discussion, but perhaps help underline that default namespaces in particular can pose problems for non-experienced XML developers.
