### ISSUE TITLE
xpath parsing of xs:* built-in list types

### ISSUE THREAD

**Issue by digre** [DeltaXML/vscode-xslt-tokenizer#140]
From XPATH-Function 3.1:
18.3 Constructor functions for XML Schema built-in list types
Each of the three built-in list types defined in [[XML Schema Part 2: Datatypes Second Edition]](https://www.w3.org/TR/xpath-functions-31/#xmlschema-2), namely xs:NMTOKENS, xs:ENTITIES, and xs:IDREFS, has an associated constructor function.

The function signatures are as follows:

xs:NMTOKENS($arg as xs:anyAtomicType?) as xs:NMTOKEN*
xs:ENTITIES($arg as xs:anyAtomicType?) as xs:ENTITY*
xs:IDREFS($arg as xs:anyAtomicType?) as xs:IDREF*

These functions result in:
XPath: Function: 'xs:NMTOKENS' with 1 arguments not found

Also, the prompt within an xpath expression does not include these functions.

**Comment by pgfearo** [comment]
Thanks for reporting this problem. This issue has now been fixed see: [Release Notes](https://github.com/DeltaXML/vscode-xslt-tokenizer/wiki/Release-Notes)
