### ISSUE TITLE
XSLT/XPath for VS Code: Error: Loading main class net.sf.saxon.Transform

### ISSUE THREAD

**Issue by Pyork** [DeltaXML/vscode-xslt-tokenizer#141]
Hello Community,

on Ubuntu 24.04 with VS Code 1.91.1 and XSLT/XPath for VS Code
v1.5.15 the XSLT/XPath extension can't find the right library though I gave the path with Java -cp option.

I checked the libraries and, indeed, the class net.sf.saxon.Transform is missing.

Given libraries in the folder ~/.vscode/extensions/deltaxml.xslt-xpath-1.5.15/xslt-resources:
deltaxml-saxon-perf-1.0-SAXON10.jar
deltaxml-saxon-perf-1.0-SAXON11.jar
deltaxml-saxon-perf-1.0-SAXON12.jar
xslt-resources/deltaxml-saxon-perf-1.0-SAXON99.jar
... and they start with com in the class name.

So I put the library with the right class path in this folder and the error remains:
saxon-pe-10.9.jar

May somebody drop me a hint please?
Thank you
York

**Comment by martin-honnen** [comment]
Did you set `XSLT.tasks.saxonJar` to the path of your Saxon jar file, as described in https://deltaxml.github.io/vscode-xslt-xpath/run-xslt.html?

**Comment by Pyork** [comment]
Hello Martin, thank you for your kind answer. Yes, I setup XSLT.tasks.saxonJar to the path of all mentioned jar files:
/home/user/.vscode/extensions/deltaxml.xslt-xpath-1.5.15/xslt-resources

The bitter truth is that this extention DeltaXML may be meant for semi-professionals working with Windows.

For that reason the Java replica .Net is requested by the bug message:
"Error: Could not find or load main class net.sf.saxon.Transform
Caused by: java.lang.ClassNotFoundException: net.sf.saxon.Transform

 *  The terminal process "java '-cp', '/home/user/.vscode/extensions/deltaxml.xslt-xpath-1.5.15/xslt-resources', 'net.sf.saxon.Transform', '-xsl:/home/pyork/Entwicklung/XSLT/Textknoten-Extraktion/Duftwerk/transform.xsl', '-s:/home/pyork/Entwicklung/XSLT/Textknoten-Extraktion/Duftwerk/data-tidied/rw1109421.html', '-o:/home/pyork/Entwicklung/XSLT/Textknoten-Extraktion/Duftwerk/xsl-out/result1.xml', '--allowSyntaxExtensions:off'" failed to launch (exit code: 1)."

I just wonder why I can't get the Windows extension of Delta XML work though I put the right Saxon jar (saxon-pe-10.9.jar) next to the others with the exact path to the Transform.class as mentioned in the error message.

May you have an idea please?
Thank you
York

**Comment by martin-honnen** [comment]
In my understanding `XSLT.tasks.saxonJar` needs to point to the Saxon JAR file itself so assuming you have your file `saxon-pe-10.9.jar` in the directory `/home/user/.vscode/extensions/deltaxml.xslt-xpath-1.5.15/xslt-resources` then you need to set `XSLT.tasks.saxonJar` to `/home/user/.vscode/extensions/deltaxml.xslt-xpath-1.5.15/xslt-resources/saxon-pe-10.9.jar`.

**Comment by Pyork** [comment]
My fault, you are right. I add the library name to the path and it works. Thank you so much!!!
Greetings from Bangkok, may you be happy!!

**Comment by Pyork** [comment]
Thank you so much. I really thought the path is enough and Java would examine each Jar on this path to find this class because DeltaXML put four Jars there. They may deliver the right package for Linux and maybe also for the Windows Office-Playstation too ;-)
