### ISSUE TITLE
Support for catalog commandline option in xslt task 

### ISSUE THREAD

**Issue by jperterm** [DeltaXML/vscode-xslt-tokenizer#17]
First, thank you for your work!
I am missing a property "catalog" or "xmlcatalog" for xslt tasks to resolve various resource locations, even xslt files for xsl:import.

By the way, is your extension able to consider (xml catalog) redirected URIs when editing? That might be a separate issue ...

Regards,
Jan

**Comment by pgfearo** [comment]
I will add the ‘catalog’ property and a number of other potential command-line arguments for Saxon to the xslt:task.

The extension cannot currently follow redirected URIs for xsl:import/xsl:include. I will add this as a separate issue.

**Comment by pgfearo** [comment]
'Catalog' and several other new command-line options now supported
