### ISSUE TITLE
How to disable (settings?) XSLT tasks autodetect?

### ISSUE THREAD

**Issue by sergey-s-betke** [DeltaXML/vscode-xslt-tokenizer#22]

**Comment by pgfearo** [comment]
Please could you expand on this, explaining more clearly what you would like disabling and why?

**Comment by sergey-s-betke** [comment]
I need disable XSLT task autodetection in VS Code. After installing this extension to VSCode I have problems with default build task. I press Ctrl+Shift+B and I see in status bar : "Task autodetection..." (excuse me for my translation from russian VSCode interface). I need to disable task autodetection feature in this extension by option in settings.json.

Thank You.

**Comment by pgfearo** [comment]
Thank you for expanding on this. I can produce a similar issue if I set an XSLT task as the default task. As a workaround, could you check that the line marked `TRY REMOVING THIS LINE` is not present and remove it - and the `,` char on the preceding line if it is. Does this stop the error message?

```
{
	"type": "xslt",
	"label": "xslt: 4. process-attributes",
	"saxonJar": "${config:XSLT.tasks.saxonJar}",
	"xsltFile": "${workspaceFolder}/process-attributes.xsl",
	"xmlSource": "${workspaceFolder}/../samples/personSplittingProcessAttributesInput-copy.xml",
	"resultPath": "${workspaceFolder}/../samples/xslt-out/processAttributesOut.xml",
	"group": {
		"kind": "build",
		"isDefault": true  <---------- TRY REMOVING THIS LINE
	},
	"problemMatcher": [
		"$saxon-xslt"
	]
}
```

**Comment by sergey-s-betke** [comment]
I install this extension to my VSCode. But I does not use xslt type tasks in my tasks.json. I have another default build type task...

**Comment by pgfearo** [comment]
Ok, thanks for that information. I will add a disable-xslt-tasks setting and I’ll investigate further for the root cause.

**Comment by sergey-s-betke** [comment]
Thank You!

**Comment by pgfearo** [comment]
I’ve now added settings to enable/disable the XSLT-JS and XSLT-Java task providers. I’ve also made changes to the task providers in the hope that it reduces their potential to conflict with other task providers.

**Comment by sergey-s-betke** [comment]
Thank You!
