### ISSUE TITLE
Filename resolution may be limited

### ISSUE THREAD

**Issue by bmix** [DeltaXML/vscode-xslt-tokenizer#29]
Trying to `xsl:include` a file via a URL style href (I tried the `file://` protocol) seems not possible. If I use a plain filesystem path, the file is found, however.

**Comment by pgfearo** [comment]
The issue here exists where the file scheme is used for both:
1. relative file references - e.g. `file:myfolder/myfile.xsl` and
2. absolute file references - e.g. `file://Users/name/myfolder/myfile.xsl`

**Comment by pgfearo** [comment]
I’ve added support for the file: scheme.
