### ISSUE TITLE
Disable CDATA formatting.

### ISSUE THREAD

**Issue by Ajaja** [DeltaXML/vscode-xslt-tokenizer#30]
Is there any way to disable  formatting of the text inside   `<![CDATA[ ... ]]>`   ?

**Comment by pgfearo** [comment]
Currently the only way would be if the parent element is an xsl:text
element or has an  xml:space="preserve" attribute. I can see this option is
a missing feature though so will mark this as a feature request.

**Comment by pgfearo** [comment]
Feature added
