### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by oblaise** [DeltaXML/vscode-xslt-tokenizer#38]
Dear All,

I'm trying to use the extension and I cannot find what I'm doing wrong. I've several working stylesheets that I use successfully or transformation but syntax highlighting doesn't work for me in vscode:

![image](https://user-images.githubusercontent.com/16148676/106031253-5b3aa980-60cf-11eb-8462-19125881d623.png)

What am I doing wrong ?

**Comment by pgfearo** [comment]
The screenshot you're showing has got syntax highlighting, different
'tokens' are shown with different colours.

Is it that syntax highlighting is not working in another part of your code?

Your screenshot shows a problem reported with the xsl:stylesheet element,
is that related to this issue? If so, please can you  attach an example
XSLT that reproduces the issue?

Note that for some themes syntax highlighting requires the VSCode semantic
highlighting setting set true, as explained in the Readme file.

**Comment by oblaise** [comment]
> The screenshot you're showing has got syntax highlighting, different 'tokens' are shown with different colours. Is it that syntax highlighting is not working in another part of your code?

No, I'm indeed referring to the issue below

> Your screenshot shows a problem reported with the xsl:stylesheet element, is that related to this issue? If so, please can you attach an example XSLT that reproduces the issue?

That's my issue that I mix up with syntax highlighting. I'm attaching a problematic stylesheet.

> Note that for some themes syntax highlighting requires the VSCode semantic highlighting setting set true, as explained in the Readme file.

I think I enabled it correctly.

[ets_calimero_group_name.zip](https://github.com/DeltaXML/vscode-xslt-tokenizer/files/5885579/ets_calimero_group_name.zip)

**Comment by pgfearo** [comment]
When I open the file in VSCode with the extension enabled I don't see the same 'Invalid attribute' message that is in your screenshot. The screenshot I've attached at the end shows that no problems are reported on my local MacOS environment.

Could you try disabling all other extensions to see if this resolves the issue? If this still fails, please could you provide more information on:

- VS Code Version:
- XSLT/XPath Extension Version:
- Your Operating System and version

![calimero](https://user-images.githubusercontent.com/2734234/106143726-16fce700-616b-11eb-9c30-2e176f1ccabd.png)

**Comment by oblaise** [comment]
I disabled all other extensions and it solved the issue. After more analysis the extension causing the issue is 'XML Tools' (https://github.com/DotJoshJohnson/vscode-xml) which is a widely used extension. It can be a bit annoying that these extensions doesn't coexist because when you work on XSLT docs you also work on XML docs.

>VS Code Version:

1.52.1
>XSLT/XPath Extension Version:

0.2.0
>Your Operating System and version

win10 20H2

**Comment by pgfearo** [comment]
I agree this is an annoyance. From [this issue](https://github.com/DotJoshJohnson/vscode-xml/issues/316) it seems that maintainer has been rather busy with other priorities.

I will see if there's anything I can do to fix compatibility this end. There is an underlying problem here because Visual Studio Code has a built-in extension for XSLT that uses the 'xsl' language id. This extension can't uses that language id because of conflicts with Visual Studio Code's built-in XSLT extension so this extension uses the 'xslt' language id instead. 

I've asked the Microsoft team through GitHub issues to help with this but unfortunately they are too busy at the moment and closed the issues with no action.

**Comment by pgfearo** [comment]
It would be very helpful if you could let me know the features missing from this extension that you use the DotJoshJohnson XML Tools extension for?

I've tried to support all the basic XML Editing features in this extension so there is a lot of overlap, but I haven't yet added XQuery support.

**Comment by oblaise** [comment]
Hard to say as both extensions were installed in parallel since a few months. I observed the incompatibility after the latest updates even if obviously some functionalities weren't working as expected before.

But now I removed the XML Tools and checked a little further. The 'Get Current XPath' could be a very good candidate to add to your extension specially as you are specifically targeting XSLT/XPath.

PS: I don't use XQuery.

**Comment by pgfearo** [comment]
Thanks for this feedback. I'll be sure to add this once I start adding the
XPath evaluator. There's an online tool that I developed a few years ago
that I may use as a starting point:

http://www.qutoric.com/xslt/analyser/xpathtool.html

**Comment by pgfearo** [comment]
I’ve added “Get current XPath” as a new feature request issue

**Comment by pgfearo** [comment]
@oblaise I've added a 'XML: Goto XPath' VSCode command to this extension.

This command can also be used as 'Get current XPath' as it pre-populates the InputBox with the current XPath location, the selected XPath can then be copied easily to the clipboard.
