### ISSUE TITLE
Error message for string literal with entity name

### ISSUE THREAD

**Issue by eluija** [DeltaXML/vscode-xslt-tokenizer#44]
When defining a string literal consisting of a entity name `('&#10;'),` an error is reported:

**String literal not terminated properly: '**

<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                version="3.0">

   <xsl:variable name="separator" select="'-'"/>
   <xsl:variable name="EOL" select="'&#10;'"/>

</xsl:stylesheet>

using v0.2.2 on Windows

**Comment by pgfearo** [comment]
Thanks for reporting this. It seems that the XPath checker is at fault here even though the semantic highlighter recognises the entity name properly.

**Comment by pgfearo** [comment]
This issue has now been fixed - to be in patch released v0.2.3
