### ISSUE TITLE
XPath: Expression context - unexpected token here: 180

### ISSUE THREAD

**Issue by eluija** [DeltaXML/vscode-xslt-tokenizer#45]
Following expression gives an error message:
`$angleInRadians div math:pi() * 180`

Adding parantheses solves the issue:
`($angleInRadians div math:pi())* 180`

`<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:math="http://www.w3.org/2005/xpath-functions/math"
                xmlns:local="urn:local-functions"
                version="3.0">

   <xsl:template match="/">
    <xsl:apply-templates select="."/>
   </xsl:template>
   
   <xsl:function name="local:radians-to-degrees" as="xs:double">
      <xsl:param name="angleInRadians" as="xs:double"/>
      <xsl:sequence select="$angleInRadians div math:pi() * 180"/>
   </xsl:function>
   
</xsl:stylesheet>`

using v0.2.2 on Windows

**Comment by pgfearo** [comment]
Thanks for reporting this. The problem here appears to be with the tokenizer, the `*` char has the wrong token type.

**Comment by pgfearo** [comment]
Work in progress. The `()` in `math:pi()` is treated as a single token, instead of the `)` char - the test for `*` multiplication operator (instead of wildcard, occurrence indicator etc.) needs to check for this preceding `()` token.

**Comment by pgfearo** [comment]
This issue has now been fixed. Will be in patch release v0.2.3
