### ISSUE TITLE
Ctrl+click on function name - Unable to resolve resource

### ISSUE THREAD

**Issue by eluija** [DeltaXML/vscode-xslt-tokenizer#48]
I have a 'master.xslt' that is importing a 'functions.xlst'.
Ctrl+click on the href of the import statement works correctly now. Thanks !

However Ctrl+click on the function name reference in eg. a select="..." gives a similar error message :
`Unable to open 'functions.xslt': Unable to resolve resource c:%5CTemp%5Ctest2%5Cfunctions.xslt.`

[test.zip](https://github.com/DeltaXML/vscode-xslt-tokenizer/files/6108841/test.zip)

(Running on Windows 10)

**Comment by pgfearo** [comment]
Thanks for reporting this I will investigate further using your attached zip and report back.
