### ISSUE TITLE
Support for calls to msxsl scripts

### ISSUE THREAD

**Issue by bejo73** [DeltaXML/vscode-xslt-tokenizer#53]
When developing xslt for BizTalk / Azure, it is quite common to call scripts within the xslt.

Now this indicates error:
XPath: Function: 'userCSharp:CheckPositiveNumber' with 1 arguments not found

It would be nice if this could be allowed.

xmlns:msxsl="urn:schemas-microsoft-com:xslt

<xsl:variable name="positiveInvoiceAmount" select="userCSharp:CheckPositiveNumber($invoiceAmount)" />

<msxsl:script language="C#" implements-prefix="userCSharp">
  	<![CDATA[
		public bool CheckPositiveNumber(string number)
		{
      		return System.Convert.ToDouble(number.Replace(".",","))> 0;
		}
	]]>
  </msxsl:script>

**Comment by pgfearo** [comment]
The focus of this project is XSLT 3.0 (or later). As such, I won't be adding features specifically for MSXSL extension instructions. MSXSL still only supports XSLT 1.0 (which is over 10 years old).

You could prevent these reported errors by declaring MSXSL extension function stubs with the appropriate namespace in an imported XSLT file. I'm unsure however whether this will affect the behaviour of MSXSL if you do this.
