### ISSUE TITLE
Finished Configuring  "xslt-js" task with xslt3 node_module, but getting Error 193 in VS Code: A native exception occurred during launch.

### ISSUE THREAD

**Issue by atifMalik** [DeltaXML/vscode-xslt-tokenizer#54]
Thank you for this VS Code extension. 
I just finished configuring a VS Code task with following tasks.json file. Every time I try to run this task on my Windows machine (Shift+Ctrl-B), I get an error in my "Terminal" window. The error says "The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 193)."

I have also navigated to the node_modules/.bin folder, and tried running the "xslt.ps1" command from a PowerShell Command Window. On running "xslt.ps1" script from PowerShell, I get an error saying "Command line option -s requires a value". 
I have also pasted the PS command (below) that I'm using to run the "xslt.ps1" script. Could this be because I haven't configured my VS Code properly, or am I missing something here. Any help would be appreciated, thanks again for the extension! 

PS Command:
.\xslt3.ps1 -xsl:C:\Code\Biogen\Xslt Playground\src\CCDA-to-SDA.xsl -s:C:\Code\Biogen\Xslt Playground\data\Test_CCDA.xml -o:C:\Code\Biogen\Xslt Playground\xslt-out\result1.xml val1=atif

Tasks.json:
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "xslt-js",
			"label": "Demo1 Xslt",
			"nodeModulesFolder": "${workspaceFolder}\\node_modules",
			"xsltFile": "${workspaceFolder}\\src\\CCDA-to-SDA.xsl",
			"xmlSource": "${workspaceFolder}\\data\\Test_CCDA.xml",
			"resultPath": "${workspaceFolder}\\xslt-out\\result1.xml",

			"parameters": [
				{
					"name": "val1",
					"value": "atif"
				}

			],

			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher": [
				"$saxon-xslt-js"
			]
		}
	]
}

**Comment by pgfearo** [comment]
Thanks for reporting this issue. I think the problem here is with the space character in the the path that follows the  '-s:'. The nodejs command line interface for SaxonJS has an issue where it escapes space characters in a path to %20 as if it were a URL. I have reported this issue to Saxonica and it should be fixed in the next SaxonJS release. You get a slightly different error from the terminal because the -s: argument is not enclosed in quotes.

**Comment by atifMalik** [comment]
Hi Phil,
Thanks for replying. 
So I've tried different methods of passing arguments into the PowerShell Script (not via VS Code, I opened a separate PowerShell Command Line window on my Windows machine), but nothing worked. This PS script is located at "\node_modules\.bin\xslt3.ps1". This PS script just passes the arguments to the xslt3.js module, that's all that this PS script is doing.

I then opened a regular "node" command line window, and ran the following command:
node xslt3.js -xsl:"C:\Code\Biogen\XsltTransforms\src\CCDA-to-SDA.xsl" -s:"C:\Code\Biogen\XsltTransforms\data\Test_CCDA.xml" -o:"C:\Code\Biogen\XsltTransforms\xslt-out\result1.xml"

This above node command works just fine (I was getting some compile errors, but that's because my XSLTs are malformed).
As you can see, the paths do not have any spaces in them, and are also enclosed in double-quotes. 

So, it looks like the problem is passing arguments from PowerShell (PS) script onto the node module "xslt3.js". 

PS takes arguments in the form xslt3.ps1 -xsl "<path-to-xsl>" -s "<path-to-xml>" (there is a space between -s and "<path-to-xml>"

Node command take arguments in the form:
node xslt3.js -xsl:"<path-to-xsl>" -s:"<path-to-xml>" (there is a colon : between -s and "<path-to-xml>".

Phil, I also watched your YouTube video on how to set this up in VS Code. In the video you are using a Mac machine, where I'm using a Windows machine. 
So, I'm wondering if you have any recommendations on how to get this working in VS Code on my machine. I appreciate your help and thanks again! - Atif

**Comment by pgfearo** [comment]
Your extra info helps confirm this is related to space characters in the path specified in the -s: argument.

This known is logged here as 'upstream bug'  [issue #47](https://github.com/DeltaXML/vscode-xslt-tokenizer/issues/47) in this repo. Here is the relevant Saxonica issue [Bug #4925](https://saxonica.plan.io/issues/4925).

In the mean time I would recommend, if you can (and don't require the Saxon-JS extensions), installing Java and using the Java release of Saxon-HE along with the corresponding task. This is documented at:[ Saxon Configuration for Java](https://github.com/DeltaXML/vscode-xslt-tokenizer/wiki/XSLT-Tasks#saxon-configuration-for-java).

**Comment by atifMalik** [comment]
Hi Phil, 
Thanks for your reply. 
I'm sorry, maybe I'm missing something here. [Bug #4925](https://saxonica.plan.io/issues/4925) says that this was resolved; it says it was resolved by Norm Tovey-Walsh. But I wasn't able to find the updated xslt3.js anywhere? Would you know where I can find the updated xslt3 npm module? 
Also the issue seems to be passing arguments from Windows PS onto the xslt3.js node module. Running the xslt3.js with a "node" module command does not give any (space related) errors. It runs fine when I use the following node command:

xslt3.js -xsl:"C:\Code\Biogen\XsltTransforms\src\CCDA-to-SDA.xsl" -s:"C:\Code\Biogen\XsltTransforms\data\Test_CCDA.xml" -o:"C:\Code\Biogen\XsltTransforms\xslt-out\result1.xml"

So the xslt3.js node command works fine. And also, if you look at the (node) command I pasted right above, you can see that there are not spaces in the any of the paths to -xsl or -s or -o options. 

I may be missing something here, but I'd really appreciate if you could please expand on your answer! Thanks again !

**Comment by pgfearo** [comment]
You can't find the updated xslt3 release that fixes _Bug #4925_ because Saxonica are not yet ready to publish a new release. 

_Bug #4925_ currently has a status of **resolved**.  This just means that the fix has been committed locally on their version control system. The status will change to **closed** once there is a new release.

Until there is a new release of SaxonJS you should either use source file paths with no spaces (as you illustrate above) or switch to using the Java version of Saxon.

Hopefully this is now clear but please let me know if there are further issues.
