### ISSUE TITLE
XPath: Undeclared prefix in name: 'h:table'

### ISSUE THREAD

**Issue by vnesterovsky** [DeltaXML/vscode-xslt-tokenizer#61]
Plugin does not see namespace declaration:

```
<xsl:function name="t:html-to-csv" as="xs:string*">
  <xsl:param name="html" as="element()"/>

  <xsl:sequence xmlns:h="http://www.w3.org/1999/xhtml" 
    select="$html!descendant-or-self::h:table[1]!h:tr!t:get-csv-line((h:td | h:th)!xs:string(.))"/>
</xsl:function>

```

**Comment by pgfearo** [comment]
Thank you for reporting the spurious problem reporting for this issue and in issues #57, #58, #59, #60. 

The latest update (v0.2.8) fixes these issues: Please see the [Release Notes](https://github.com/DeltaXML/vscode-xslt-tokenizer/wiki/Release-Notes)
