### ISSUE TITLE
Incompatability with bpmn-iobpmn-io/vs-code-bpmn-io

### ISSUE THREAD

**Issue by dignin** [DeltaXML/vscode-xslt-tokenizer#62]
Hey, after tracing back (with the help of the bpmn-io team) the collision with your extension in the following post:

https://github.com/bpmn-io/vs-code-bpmn-io/issues/96#issuecomment-839514257

I'd like to pass it on to you, that your plugin may break compatibility with other plugins regarding bpmn as well. I would love to be able to use both extensions simultaneously. Can you take a look if it's fixable on your side?

How to reproduce, vs-code-bpmn-io, then install your plugin. Notice the functionality from bmpn-io is gone. It just requries deactivation of your plugin, to make vs-code-bpmn-io work again.

Hope to hear from you. If you need more information, let me know.

**Comment by pgfearo** [comment]
I'll look into this compatibility and update here as soon as I have more info. 

The quickest solution would be to modify `package.json` and remove `bpmn` from the list of XML file extensions (which was copied from VSCode's built in XML extension).

Obviously though I'd like to see if there are changes I can make to allow both extensions to function properly with this file type, for example to allow this extension's XML formatting feature.

**Comment by pgfearo** [comment]
To fix this issue I've added the `bpmn` language id specifically to this extension - instead of using the generic 'xml' language id. This extension now explicitly supports XML formatting, syntax highlighting and basic XML syntax checking for BPMN files.
