### ISSUE TITLE
XPath: The variable/parameter: $id: cannot be resolved here, but it may be defined in an external module.

### ISSUE THREAD

**Issue by vnesterovsky** [DeltaXML/vscode-xslt-tokenizer#63]
New bug for new release: :-)

```xslt
    <xsl:sequence select="
      let $name := 'a' return
      let $id := 'b' return
        map { $id: $name }"/>
```

In fact, several errors are reported here:
  XPath: Undeclared prefix in name: '$id:'
  XPath: Expression context - unexpected token here: $name 
  XPath: The variable/parameter: $id: cannot be resolved here, but it may be defined in an external module.

Notice that: `map { $id : $name }` works as expected.

**Comment by pgfearo** [comment]
Thanks for reporting this.

It seems that this problem is specific to variables used in maps constructors where the `:` char immediately follows the variable name.  Further investigation shows the problem lies with the tokenizer combining `$id:` into a single token - hence the odd error messages.

**Comment by pgfearo** [comment]
Fixed
