### ISSUE TITLE
Cannot create process, error code: 193 (Windows 10)

### ISSUE THREAD

**Issue by Denyerec** [DeltaXML/vscode-xslt-tokenizer#66]
When attempting to follow the task instructions in the Wiki on running a basic xslt-js transform I receive the following:

``` The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 193). ```

The generated commandline is:
``` G:\SVGTools\node_modules\.bin\xslt3 -xsl:G:\SVGTools\source.xslt -s:G:\SVGTools\output\data.xml -o:G:\SVGTools\xslt-out\result1.xml < ```

If I copy and paste the command to a cmd window or the VSCode terminal it executes correctly, however running the task via Ctrl+Shift+B results in the ErrCode193

I think it's because on the cmdline or directly in the terminal it picks up the xslt3.cmd file and processed things correctly, wheras when issued from the task it's trying to run "xslt3" directly which isn't a valid executable, however I have no idea how to change this if it's actually the source of the issue.

Apologies if this is completely the wrong place to raise this, I arrived here whilst following the documentation for the deltaxml.xslt-xpath extension docs.

**Comment by Denyerec** [comment]
**Workaround:**

Editing line 152 of %USERDIR%\.vscode\extensions\deltaxml.xslt-xpath-0.2.8\out\saxonJsTaskProvider.js to read:

``` const processExecution = new vscode.ProcessExecution(nodeModulesPath + 'xslt3.cmd', commandLineArgs.concat(xsltParametersCommand)); ```

Causes the correct windows commandline to be issued, allowing the tool to run. It could be that my shell configuration (Windows default, as I've not modified anything) needs tweaking, but I don't know where to start when it comes to that!!

**Comment by pgfearo** [comment]
Thanks for reporting this and looking into a fix that will work for the Windows default.  I will adapt this so that  it will generate the right command for Windows or /Linux/MacOS.

**Comment by pgfearo** [comment]
This has been been fixed by using the `.cmd` filename extension for Windows as suggested. The executable though is now `npx` with an `xslt3` argument. As `nsx` auto-locates the module, the nodeModulesFolder path setting no longer needs to be used in the xslt-js task (if it is set it is unused).

**Comment by Denyerec** [comment]
Superb - thanks for your super-fast attention on this one!
