### ISSUE TITLE
Validation errors in editors with  XSLt documents

### ISSUE THREAD

**Issue by zpleal** [DeltaXML/vscode-xslt-tokenizer#80]
I am using XSLT/XPATH for Visual Studio Code with Saxon (Java) on Ubuntu 20.04.2 LTS. I manage to run transformations. However, I get validation errors in editors with XSLt files.

If I create an XSLt file as simple as

<?xml version="1.0"?>
<xsl:stylesheet  version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
</xsl:stylesheet>

The output in PROBLEMS is the following

  XSLT: Invalid attribute on element 'xsl:stylesheet': 'version'
  There are '45' errors in 'schema-for-xslt30.xsd'.

(This last line is followed by 45 error lines)

If I change  version="3.0"  to a different number (e.g. "2.0") them the second line (the 45 errors) disappears. If I remove the attribute or give it a non-numeric value then the error is "Attribute version is required in element xsl:stylesheet".

If I replace xsl:stylesheet by xsl:transform, the result is the same.

I also have the XML Language Support by Red Hat installed. But event with this extension disabled the result is the same.

Any idea of what I might be doing wrong?

**Comment by pgfearo** [comment]
When you create the XSLT file, do you still get errors when you save it with a '.xsl' file extension? Also, what 'language' is shown in the VS Code status bar?

Note: You've mentioned that the problem occurs even with Red Hat disabled, unfortunately (due to VS Code problems based on a lot of legacy) these two extensions can't co-exist, so you're doing the right thing - disabling Red Hat when editing

**Comment by zpleal** [comment]
Hi Phil,

I installed the XSLT/XPath extension in a fresh VSCode installation 
without problems.

Them, I installed the Red Hat XML tools extension and the same kind of 
problems returned, this time on XML Schema files.

After uninstalling and reinstalling a few times both extensions I 
managed to get them working on the same workspace.

Thanks!
zp


Às 14:17 de 10/08/21, Phil Fearon escreveu:

**Comment by pgfearo** [comment]
Here's an issue link, I've submitted others also:  https://github.com/microsoft/vscode/issues/99427

I am having to use 'xslt' for the programming language  ID instead of 'xsl' to prevent VSCode from applying XML features that the extension does better, problems are especially associated with the built in XML TM Grammar. RedHats extension conflicts because it uses 'xsl' - it doesn't need to parse XML attributes that hold XPath expressions or text-value-templates or attribute-value-templates etc.

**Comment by pgfearo** [comment]
Glad you got this extension and the Red Hat XML extension to both work, I will have to see if there's anything I can do to improve things without the VS Code teams help as they have lots of higher priorities. (I'm especially impressed by their new Notebooks support which seems to fit well with my XPath needs)

**Comment by zpleal** [comment]
I managed to make both extensions work but this doesn't completely solve 
my problem.

It may sound strange but my issue now is that I cannot reproduce 
situation I had when I first installed these extensions.

I teach a course on XML and the syllabus includes both validation (DTD 
and XML Schema) and transformation (XST and XQuery).

I am considering to switch to VSCode but I need to select a set of 
compatible extensions. At least, I need to figure out an installation 
procedure that works.

I uninstalled and installed again both extensions, in any order, and now 
they both work just fine. I even removed their directories  form 
~/.vscode/extensions/  (uninstall doesn't do it) and also removed the 
XSD and DTD files in ~/.lemminx. They always both work just fine.

Do you have any idea of any other files that may be created/modified by 
you extension that are not in 
~/.vscode/extensions/deltaxml.xslt-xpath-0.3.6/  or ~/.lemminx/cache/ ?

Thanks!

Às 18:52 de 11/08/21, Phil Fearon escreveu:

**Comment by pgfearo** [comment]
My extension doesn't intentionally change any of the user or workspace environment. The workspace tasks.json file may be created or modified but this is done in the regular way via the Tasks API.

I can reproduce the symptoms you saw (with only my extension installed), if I create a file with a '.xml' file extension (instead of '.xsl') and then type xslt elements adding the xslt namespace to the root element. I should just show a warning message in this case and am intending to fix this.

**Comment by riri** [comment]
Hello

I have the same kind of problem, first error on a well formated xsl file is `: XSLT: Invalid attribute on element 'xsl:stylesheet': 'version'`

This worked a few weeks ago, I suppose an update made it failing.
For xml I have 2 extensions in vscode (both works concurrently so far) :
* XML Tools (https://github.com/DotJoshJohnson/vscode-xml)
* XSLT/XPath (https://github.com/DotJoshJohnson/vscode-xml)

The file has a `xsl` extension, and the language can be XML or XSL, I have errors reported.
A weird thing is that now XML is selected by default (while it was XSL or XSLT before - I don't remember exactly)
If I select the XSLT language, there is no syntax highlight anymore (and still have the errors)

![list of errors](https://i.imgur.com/RkQIVGa.png)

For info, here is the beginning of my xsl:
```xsl
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
                version="1.0">
```

**Comment by zpleal** [comment]
I suggest you avoid using more than one VSCode extension that operates on XML files. If you are using XSLT/XPATH then disable all the others (and restart). It usually solves this kind of problem.

**Comment by pgfearo** [comment]
@riri The suggestion by @zpleal is what I would advise also. Both extensions are competing to apply features to files with the '.xsl' extension and in this case the DotJoshJohnson XML extension wins and prevents our extension from working properly.

The DotJoshJohnson XML extension is not currently being maintained. Are there specific XML features you need that DeltaXML's XSLT/XPath extension doesn't provide?

As noted earlier in this thread, this extension _can_ coexist with the RedHat XML extension (but problems were experienced earlier) that provides features such as XML Schema based validation/auto-completion.

Please not also that, if you need standalone XPath features,[ DeltaXML's XPath Notebook extension](https://marketplace.visualstudio.com/items?itemName=deltaxml.xpath-notebook) is designed to build on DeltaXML's XSLT/XPath language extension.

**Comment by riri** [comment]
Well, I installed the XML Tools before the XSLT one, and it stayed there.
I have no specific reason to keep the XML Tools extension if the XSLT one covers the features.

I disabled the XML Tools extension and it solved my issue. Thanks.

**Comment by TBugReporter** [comment]
I guess the simplest thing I could say is "me, too".  My initial query about this (before I had any clue what could be causing it) is [here](https://stackoverflow.com/questions/78877623/why-is-vsc-throwing-these-silly-non-errors-when-i-edit-xsl).
