### ISSUE TITLE
Build Task command line contains extraneous commas with Windows Environments (Powershell7)

### ISSUE THREAD

**Issue by TheEnglishman-1966** [DeltaXML/vscode-xslt-tokenizer#82]
I'm following the Youtube 'HOWTO' - https://www.youtube.com/watch?v=fdxfXaJw6SY

The BuildTask, when run, puts commas in between the attributes and throws errors:

PS F:\Tools\Powershell> npx.cmd xslt3, '-xsl:f:\Tools\Powershell\XSLDemo\src\demo.xsl', '-s:f:\Tools\Powershell\XSLDemo\data\colours.xml', '-o:f:\Tools\Powershell\XSLDemo\xslt-out\result1.html'
C:\PROGRA~1\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:296
      throw invalidTagName(spec)
      ^

Error: Invalid tag name "xslt3,": Tags may not have any characters that encodeURIComponent encodes.
........

However, if I remove the commas everything runs correctly:

PS F:\Tools\Powershell> npx.cmd xslt3 '-xsl:f:\Tools\Powershell\XSLDemo\src\demo.xsl' '-s:f:\Tools\Powershell\XSLDemo\data\colours.xml' '-o:f:\Tools\Powershell\XSLDemo\xslt-out\result1.html'
npx: installed 4 in 2.928s

This could be my setup error(s) as I'm new to VSCode and am running this via SSH onto another computer.

**Comment by pgfearo** [comment]
Thanks for reporting this issue.

The Saxon task provider for this extesnion doesn't generate the command-line string directly, instead it uses calls [vscode.ProcessExecution()](https://code.visualstudio.com/api/references/vscode-api#ProcessExecution) with the command and an array of command line arguments.

I suspect that this is somehow related to using SSH or an SSH related extension as there weren't any problems when I tested the task provider with powershell locally. I'm afraid I don't know anything about SSH in this context, are you using an SSH extension for VS Code? Do you still have the same problem without using SSH?

**Comment by pgfearo** [comment]
I'm closing this issue as there's not enough information here to proceed.
