### ISSUE TITLE
XSLT Task with initialTemplate still expects xmlSource

### ISSUE THREAD

**Issue by frankweenink** [DeltaXML/vscode-xslt-tokenizer#85]
When specifying an initial template in a task it still expects an xml source. 

To reproduce, create a task without xmlSource, but with an initialTemplate:
```json
{
			"type": "xslt",
			"label": "xslt: Saxon Transform (New)",
			"saxonJar": "${config:XSLT.tasks.saxonJar}",
			"xsltFile": "convert.xsl",
			"resultPath": "-",
			"initialTemplate": "main",
			"group": {
				"kind": "build"
			},
			"problemMatcher": [
				"$saxon-xslt"
			]
}
```

Run the task. The command line will show the empty -s: parameter (and Saxon shows this error):

`-xsl:convert.xsl -s: -it:main -o:-`

**Comment by pgfearo** [comment]
Fixed in latest release
