### ISSUE TITLE
Integrate support for EXSLT

### ISSUE THREAD

**Issue by jvogel-cur** [DeltaXML/vscode-xslt-tokenizer#94]
Is there a plan to integrate EXSLT functions support?

Everything works great, only the error messages are confusing.

![image](https://user-images.githubusercontent.com/61142528/150856049-a8a56113-d651-4c84-b5c5-5f4372b344d7.png)

**Comment by pgfearo** [comment]
The approach here would be to avoid checking the existence/arity of functions in the EXSLT namespace.

I am however not planning to actively support EXSLT (through auto-completion etc.) as this extension is intended for XSLT 3.0 and XPath 3.1 which supersede the EXSLT.

**Comment by pgfearo** [comment]
Functions found to be in the 5 documented EXSLT namespaces are now no longer checked, therefore problems are not reported. There's also auto-completion for the `http://exslt.org/common` namespace declaration on the root element.

I won't be adding further support for EXSLT going forwards as EXSLT was superseded many years ago.
