### ISSUE TITLE
Some issues with XSLT parser

### ISSUE THREAD

**Issue by softinn72** [DeltaXML/vscode-xslt-tokenizer#97]
Hello,
first of all thanks a lot for the great VSCode extension, it's very useful and much appreciated!

While working on a quite complex XSLT stylesheet, I have found a couple of weird errors raised by the static analysis parser which I do not understand. 

For example, it seems that the fn:concat() function is marked as error whenever it's called only with 2 parameters:
![immagine](https://user-images.githubusercontent.com/15148725/157681861-1ce2ec3a-9005-4a88-983e-e14a87b88416.png)
The error in the popup is "'fn:concat' with 2 arguments not found". 
If I add an empty string as the 3rd parameter the error disappears. 

Another weird error is raised whenever in a select expression I use the encoded <= symbol:
![immagine](https://user-images.githubusercontent.com/15148725/157682637-f9a94e09-ba10-4925-bf2f-61f193f22516.png)
The error here is "Expression context - unexpected token here: =".
As a workaround I could invert the order of the compared items, but in this specific case I find the logic more legible when <= is used.

I'd like to add that Saxon processes the XSLT correctly without raising any errors, so I think these 2 errors are just a problem of the plugin. Could you please have a look and let me know how if it's possible to fix them?

Thanks a lot for the attention,
Paolo

**Comment by pgfearo** [comment]
Thanks for reporting these problems. I will provide an update as soon as I can.

**Comment by pgfearo** [comment]
1. The `fn:concat` function call is now valid for 1 or more arguments (the same as a `concat` function call
2. Errors are no longer reported for operator `&lt;=` and also `&gt;=`

These fixes are included in [Release 1.2.2](https://github.com/DeltaXML/vscode-xslt-tokenizer/wiki/Release-Notes#release-122)
